language: php

php:
  - 7

global:
  - CI=true
  - CI_ENV=testing

# Recommended by Travis support
sudo: required
dist: precise

env:
  - DB=mysqli
  - DB=postgres

services:
  - mysql
  - postgresql

script:
  - php vendor/bin/phpunit -v

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test';" -uroot
  - psql -c 'create database test;' -U postgres

before_script:
  - composer install --prefer-source

