name: "Static Analysis Check"

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - '4.1'
    paths:
      - 'app'
      - 'system'

jobs:
  build:
    name: Run Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          extensions: intl
          php-version: "7.4"
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: "composer install"
      - name: "Static analysis Check"
        run: "vendor/bin/phpstan analyze --level=0 app system"