# When a PR is opened or a push is made, perform an
# architectural inspection on the code using Deptrac.
name: Deptrac

on:
  pull_request:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**.php'
      - 'system/**.php'
      - 'composer.json'
      - 'depfile.yaml'
      - '.github/workflows/test-deptrac.yml'
  push:
    branches:
      - 'develop'
      - '4.*'
    paths:
      - 'app/**.php'
      - 'system/**.php'
      - 'composer.json'
      - 'depfile.yaml'
      - '.github/workflows/test-deptrac.yml'

jobs:
  build:
    name: Architectural Inspection
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer, phive
          extensions: intl, json, mbstring, gd, mysqlnd, xdebug, xml, sqlite3

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Create composer cache directory
        run: mkdir -p ${{ steps.composer-cache.outputs.dir }}

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Create Deptrac cache directory
        run: mkdir -p build/

      - name: Cache Deptrac results
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-deptrac-${{ github.sha }}
          restore-keys: ${{ runner.os }}-deptrac-

      - name: Install dependencies
        run: composer update --ansi --no-interaction

      - name: Run architectural inspection
        run: |
            sudo phive --no-progress install --global qossmic/deptrac --trust-gpg-keys B8F640134AB1782E
            deptrac analyze --cache-file=build/deptrac.cache
