name: Automatic Code Review

on:
  pull_request:
    paths:
      - composer.json
      - spark
      - '**.php'
      - .github/workflows/test-autoreview.yml
  push:
    paths:
      - composer.json
      - spark
      - '**.php'
      - .github/workflows/test-autoreview.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  auto-review-tests:
    uses: ./.github/workflows/reusable-serviceless-phpunit-test.yml # @TODO Extract to codeigniter4/.github repo
    with:
      job-name: Automatic Code Review [PHP 8.1]
      php-version: '8.1'
      job-id: auto-review-tests
      group-name: AutoReview
